<?php

/**
 * This file is part of the spryker-community/search-debug package.
 * For full license information, please view the LICENSE file that was distributed with this source code.
 */

declare(strict_types = 1);

namespace SprykerCommunity\Yves\SearchDebugWidget\Controller;

use Spryker\Yves\Kernel\Controller\AbstractController;
use Spryker\Yves\Kernel\PermissionAwareTrait;
use Spryker\Yves\Kernel\View\View;
use SprykerCommunity\Shared\SearchDebug\Plugin\SeeSearchDebugInfoPermissionPlugin;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

/**
 * @method \SprykerCommunity\Yves\SearchDebugWidget\SearchDebugWidgetFactory getFactory()
 */
class TokenSourceController extends AbstractController
{
    use PermissionAwareTrait;

    /**
     * @var string
     */
    protected const PARAM_SKU = 'sku';

    /**
     * @var string
     */
    protected const PARAM_TOKEN = 'token';

    /**
     * The real field=>boost pairs the SRP's search query used, forwarded from the search-debug overlay
     * that generated this link — see `search-debug-product-info.twig`'s link and
     * `SprykerCommunity\Client\SearchDebug\Query\QueryFieldBoostReader`, which captured them live off
     * that query. Purely informational display data: a missing or tampered value only degrades to
     * `TokenSourceResolver`'s own fallback, never a security or correctness concern for the real search.
     *
     * @var string
     */
    protected const PARAM_BOOSTS = 'boosts';

    /**
     * @param \Symfony\Component\HttpFoundation\Request $request
     *
     * @throws \Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException
     * @throws \Symfony\Component\HttpKernel\Exception\BadRequestHttpException
     * @throws \Symfony\Component\HttpKernel\Exception\NotFoundHttpException
     *
     * @return \Spryker\Yves\Kernel\View\View
     */
    public function indexAction(Request $request): View
    {
        if (!$this->can(SeeSearchDebugInfoPermissionPlugin::KEY)) {
            throw new AccessDeniedHttpException();
        }

        // The abstract product ID never appears in the URL — only the SKU, a value already public
        // elsewhere on the storefront (PDP URLs, order confirmations), unlike the internal DB id.
        $productAbstractSku = (string)$request->query->get(static::PARAM_SKU, '');

        // Lowercased defensively: index-analyzer tokens are always lowercase (page.json `lowercase`
        // filter), and the strict token comparison downstream would otherwise report "no match"
        // everywhere for a hand-edited or re-typed URL like `?token=CABLE`. Links generated by the SRP
        // already carry lowercase tokens, so this only matters for manually altered URLs.
        $token = mb_strtolower((string)$request->query->get(static::PARAM_TOKEN, ''));

        if ($productAbstractSku === '' || $token === '') {
            throw new BadRequestHttpException('Both `sku` and `token` query parameters are required.');
        }

        $fieldBoosts = $this->sanitizeFieldBoosts((array)($request->query->all()[static::PARAM_BOOSTS] ?? []));

        $result = $this->getFactory()
            ->createTokenSourceResolver()
            ->resolve($productAbstractSku, $token, $this->getLocale(), $fieldBoosts);

        if ($result === null) {
            throw new NotFoundHttpException(sprintf('Product abstract with SKU %s not found.', $productAbstractSku));
        }

        return $this->view(
            [
                'productTitle' => $result['productTitle'],
                'productSku' => $result['productSku'],
                'token' => $token,
                'tiers' => $result['tiers'],
            ],
            [],
            '@SearchDebugWidget/views/token-source/token-source.twig',
        );
    }

    /**
     * Defensive against a hand-edited or malformed `boosts[...]` query string (e.g. a nested array value
     * where a scalar boost is expected) — drops anything that doesn't look like `fieldName => intBoost`
     * rather than letting a malformed URL throw.
     *
     * @param array<mixed> $rawFieldBoosts
     *
     * @return array<string, int>
     */
    protected function sanitizeFieldBoosts(array $rawFieldBoosts): array
    {
        $fieldBoosts = [];

        foreach ($rawFieldBoosts as $fieldName => $boost) {
            if (!is_string($fieldName) || is_array($boost)) {
                continue;
            }

            $fieldBoosts[$fieldName] = (int)$boost;
        }

        return $fieldBoosts;
    }
}
