<?php

/**
 * This file is part of the spryker-community/search-debug package.
 * For full license information, please view the LICENSE file that was distributed with this source code.
 */

declare(strict_types = 1);

namespace SprykerCommunity\Yves\SearchDebugWidget\Controller;

use SprykerCommunity\Shared\SearchDebug\Plugin\SeeSearchDebugInfoPermissionPlugin;
use Spryker\Yves\Kernel\Controller\AbstractController;
use Spryker\Yves\Kernel\PermissionAwareTrait;
use Spryker\Yves\Kernel\View\View;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

/**
 * @method \SprykerCommunity\Yves\SearchDebugWidget\SearchDebugWidgetFactory getFactory()
 */
class TokenSourceController extends AbstractController
{
    use PermissionAwareTrait;

    /**
     * @var string
     */
    protected const PARAM_SKU = 'sku';

    /**
     * @var string
     */
    protected const PARAM_TOKEN = 'token';

    /**
     * @param \Symfony\Component\HttpFoundation\Request $request
     *
     * @throws \Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException
     * @throws \Symfony\Component\HttpKernel\Exception\BadRequestHttpException
     * @throws \Symfony\Component\HttpKernel\Exception\NotFoundHttpException
     *
     * @return \Spryker\Yves\Kernel\View\View
     */
    public function indexAction(Request $request): View
    {
        if (!$this->can(SeeSearchDebugInfoPermissionPlugin::KEY)) {
            throw new AccessDeniedHttpException();
        }

        // The abstract product ID never appears in the URL — only the SKU, a value already public
        // elsewhere on the storefront (PDP URLs, order confirmations), unlike the internal DB id.
        $productAbstractSku = (string)$request->query->get(static::PARAM_SKU, '');

        // Lowercased defensively: index-analyzer tokens are always lowercase (page.json `lowercase`
        // filter), and the strict token comparison downstream would otherwise report "no match"
        // everywhere for a hand-edited or re-typed URL like `?token=CABLE`. Links generated by the SRP
        // already carry lowercase tokens, so this only matters for manually altered URLs.
        $token = mb_strtolower((string)$request->query->get(static::PARAM_TOKEN, ''));

        if ($productAbstractSku === '' || $token === '') {
            throw new BadRequestHttpException('Both `sku` and `token` query parameters are required.');
        }

        $result = $this->getFactory()
            ->createTokenSourceResolver()
            ->resolve($productAbstractSku, $token, $this->getLocale());

        if ($result === null) {
            throw new NotFoundHttpException(sprintf('Product abstract with SKU %s not found.', $productAbstractSku));
        }

        return $this->view(
            [
                'productTitle' => $result['productTitle'],
                'productSku' => $result['productSku'],
                'token' => $token,
                'tiers' => $result['tiers'],
            ],
            [],
            '@SearchDebugWidget/views/token-source/token-source.twig',
        );
    }
}
